### ISSUE TITLE
Code rewriter based on static analysis

### ISSUE THREAD

**Issue by chillu** [silverstripe/silverstripe-upgrader#51]
# Overview

The upgrade guide contains hundreds of API changes, which will be impossible for a developer to keep in their head while reviewing a codebase. While there's APIs that have fundamentally changed their behaviour (e.g. asset abstraction), there's many that are just renamed and could be replaced automatically if we were sure about the context they're used in. [phpstan](https://github.com/phpstan/phpstan) is a static analysis tool based on the [phpparser](https://github.com/nikic/PHP-Parser) we already use. We've added a [poor man's static analysis](https://github.com/silverstripe/silverstripe-upgrader/pull/44) already to provide warnings, but not with enough confidence to actually rewrite the code.

# Acceptance Criteria

 * Rewrites code based on existing `warnings` rules
 * Retains ability to provide warnings where code can't be automatically fixed
 * Rewrites static methods and properties based on their class
 * Rewrites instance methods and properties based on hints provided by phpstan
 * Works with `<class>::create()`
 * Does not conflict with existing class name rewrites in the upgrader
 * Clearly separates rewrites from warnings in the output
 * Bonus points: Works with `Injector::inst()->create(<class>)`
 * Bonus points: Works with `Extension`

# Notes

 * Could work with phpstan rules provided by https://github.com/SilbinaryWolf/silverstripe-phpstan
 * We should PoC this before diving in too deep
 * Assumes this does not substantially increase the runtime (<5 mins on a standard codebase)
 * Does not require changes to phpstan (otherwise the cost/benefit ratio won't work any more)
 
# Tasks

 - Update php-parser to 3.1
 - Add phpstan/phpstan as dependency
 - Upgrade warnings to use phpstan hints
 - Add new config for rewrites (similar format to warnings config)
 - Ensure rewrites work
 - Update unit tests
 - Update modules `.upgrade.yml` for all core modules
 - Update docs
 - Test with sample site
 
# PRs:

Main upgrader:

 - [x] https://github.com/silverstripe/silverstripe-upgrader/pull/57
 
Rules upgrades:

 - [x] https://github.com/silverstripe/silverstripe-cms/pull/2114
 - [x] https://github.com/silverstripe/silverstripe-framework/pull/7903
 - [x] https://github.com/silverstripe/silverstripe-assets/pull/120
 - [x] https://github.com/silverstripe/silverstripe-versioned/pull/128

**Comment by chillu** [comment]
@SilbinaryWolf Do you think this would be feasible based on your experience with phpstan?

**Comment by SilbinaryWolf** [comment]
@chillu I haven't tried using it's parsing logic on it's own so I'm not sure how easy it is to utilize outside of using the provided `phpstan` PHP binary. (If using it this way is something you can't figure out in a timely manner, I've found the PHPStan dev "ondrejmirtes" to be incredibly helpful, so raise an issue)

It's also worth noting that my module isn't feature complete, it can infer types from `Page::get()` but it won't infer from `<class>::create()` yet, it would need an `ObjectStaticReturnTypeExtension` that handles that.

My module bootstraps and uses the config system so that *eventually* I can infer the correct class when using `Injector::inst()->get()` and I'm not sure how that'll affect integration with your current upgrader code.
https://github.com/SilbinaryWolf/silverstripe-phpstan/blob/master/bootstrap.php#L14

**Comment by chillu** [comment]
Thanks for the fast feedback! Yeah bootstrapping the injector and YAML config on a project that hasn't been upgraded yet sounds like a hassle. It would essentially require a standalone use of the YAML config module, without executing any PHP code (incl. `_config.php`) in the codebase to be upgraded. I'm not sure how feasible that is. Alternatively, we could export a class map from the working 3.x project *before* switching any dependencies to 4.x

**Comment by tractorcow** [comment]
WIP at https://github.com/open-sausages/silverstripe-upgrader/tree/pulls/intelligent-rewrite

Added some tasks to the parent comment on this story.

**Comment by tractorcow** [comment]
@chillu I've discovered we can't implement this without bumping php requirement to php7 (preferrably php 7.1). Is this going to be a deal breaker?

**Comment by tractorcow** [comment]
PHPStan also can't analyse code without loading classes into memory; It can't do passive analysis only.

This may make it impossible to use when in the middle of an upgrade on a breaking site. E.g.

```php
class MyTest extends SapphireTest {}
```

Will fail to load reflection in phpstan because it hasn't been upgraded yet.

**Comment by tractorcow** [comment]
This story is super hard.

**Comment by silbinarywolf** [comment]
Is it possible to abuse the `class_alias()` functions in conjunction with the `.upgrade.yml` files?
ie.
```
$frameworkFile = Symfony\Component\Yaml\Yaml::parseFile(BASE_PATH.'\vendor\silverstripe\framework\.upgrade.yml');
if (!isset($frameworkFile['mappings'])) {
	throw new Exception('Missing "vendor\silverstripe\framework\.upgrade.yml".');
}
$cmsFile = Symfony\Component\Yaml\Yaml::parseFile(BASE_PATH.'\vendor\silverstripe\cms\.upgrade.yml');
if (!isset($cmsFile['mappings'])) {
	throw new Exception('Missing "vendor\silverstripe\cms\.upgrade.yml".');
}
$classSS3toSS4 = array_merge($frameworkFile['mappings'], $cmsFile['mappings']);
foreach ($classSS3toSS4 as $ss3ClassName => $ss4ClassName) {
	if (!class_exists($ss4ClassName) ||
		class_exists($ss3ClassName)) {
		// !class_exists($ss4ClassName) - This is to ignore template remapping and other misc non-classes.
		// class_exists($ss3ClassName - This is to stop redeclarations of SITETREE/CMSSIteTreeFilter_PublishedPages
		continue;
	}
	class_alias($ss4ClassName, $ss3ClassName);
}
```

**Comment by tractorcow** [comment]
It's not that simple; You would need to do this all the way up the chain for all classes. Some classes simply don't exist at all in the upgrade (e.g. object), so as soon as you hit that one class your project would crash upgrade.

Instead, I've decided to look at creating a separate post-upgrade task for more advanced upgrade tasks. This way you can run the basic upgrader first, and then apply manual changes (based on warnings), but then run the "deep" upgrader, which will actually load your classes into memory.

**Comment by tractorcow** [comment]
I got as far as https://github.com/open-sausages/silverstripe-upgrader/commit/532182b23e854d02e0b27e68ebc394f436de0682 before it crashed.

**Comment by silbinarywolf** [comment]
Ah yep, damn. I forgot about the fact that `Object` doesn't exist.
Then there'd probably also be additional issues with some classes having different function signatures and whatnot too. 
(ie. `RequestFilter`)

With your latest comment, are you saying the deep upgrader was a no-go or?

**Comment by tractorcow** [comment]
No it's a-go, it just requires another approach.

I've started with documentation. See if https://github.com/open-sausages/silverstripe-upgrader/tree/pulls/intelligent-rewrite#post-upgrade-of-code makes sense to you.
