### ISSUE TITLE
Support devs upgrading with incompatible modules

### ISSUE THREAD

**Issue by sminnee** [silverstripe/silverstripe-upgrader#77]
## Acceptance Criteria

 * As a developer with composer managed custom or community modules which aren't yet upgraded, I have a path to complete the upgrade of my project
 * As part of the upgrade command, the upgrader automatically determines incompatible modules and makes suggestions on how to proceed with each of them
 * There's a clear path to getting my project with incompatible modules into a state where I can successfully run `composer update`

## Notes

 * The upgrader already lists incompatible modules

## Implementation Suggestion

If you're upgrading a site with modules that need to be upgraded, you can get into a bit of a catch-22: you can only upgrade your project by removing those modules, but those modules might be necessary for the functioning of your site.

One way around this is a sequence such as:

 * Create `ss4` branches of all your modules, on your main repo, so that `dev-ss4` is now a composer version you can use
 * Update the requirements in composer.json so that framework is `^4`
 * Update the requirements of your main project for all those dependencies to `dev-ss4`

It would be nice if `upgrade-code recompose` could assist with this.

 * For modules that don't have a supported version available, ask whether they'd like to create one. If no, the module can be removed as is the current behaviour.
 * If the user says yes:
   * Check out the git source of module
   * Ask whether the user has commit rights to the main repo or if they would like to use a different repo address
     * If a different repo address is created, add that as a git remote, and put it in the "repositories" section of the root composer.json
   * Create a branch of the form "ss4-upgrade" (maybe allow users to enter a different branch name)
   * `git push -u` that branch to the relevant remote
   * Update the version requirement in the root project's composer.json to "dev-ss4-upgrade"

This will leave you ready to run `upgrade-code upgrade` and `upgrade-code inspect` on the module, and push any changes to your newly created branch

## Tasks
- [x] Flesh out the 3 bullet points in `vendor/silverstripe/framework/docs/en/03_Upgrading/index.md:354` (https://docs.silverstripe.org/en/4/upgrading/upgrading_project/#resolving-conflicts)
- [x] Add suggested steps to `silverstripe-upgrader/src/Composer/Rules/Rebuild.php:214`

## Pull Requests
- [x] https://github.com/silverstripe/silverstripe-upgrader/pull/160
- [x] https://github.com/silverstripe/silverstripe-framework/pull/8836
