### ISSUE TITLE
Add a "module upgrade" mode

### ISSUE THREAD

**Issue by maxime-rainville** [silverstripe/silverstripe-upgrader#85]
# Overview

There's a few things we could do to make the upgrader more helpful for package maintainers. Some of these are easiest done as docs, others need to be part of the upgrader tooling. 

# Acceptance Criteria

 * As a module maintainer, I have a clearly documented path to upgrade my module to 4.x
 * The upgrader tooling does not actively prevent me from achieving this
 * As a developer upgrading a custom project, I'm not confused by module upgrading advice
 * I can easily choose my path when starting to look into upgrading (modify landing page)

# Potential tasks

* Adjust `recompose` so it can update your package type to `silverstripe-vendormodule` and auto-add the `vendor-plugin` to your dependencies ;
* Disable recipe equivalence rule in `recomposer` ;
* Add some logic to update unit test (could be helpful for regular projects as well);
  * Remove silverstripe/travis-support from dependencies
  * Add a bootstrap attribute to `phpunit.xml.dist`.
* Add logic to rename `code` to `src` ;
* `add-namespace` could auto-update the package name and get it's namespace from there.
* Add namespace could update composer.json with a `psr-4` entry.
* Add some dedicated doc for updating packages.

# Related issue
* #72 

# Tasks
* [x] Step 0 - Discus how to branch off your module
* Step 1 - Upgrade your dependencies
  * [ ] ~~Add a flag to `recompose` so we don't substitute recipes~~
  * [x] Document how to switch to a vendormodule
  * [x] Document how to update your dependencies as a module maintainer
* Step 2 - Update your environment configuration {#env}
  * [x] Quick blurb about the new way to fetch environment variables.
* Step 3 - Namespacing your project (optional)
  * [x] Check if we can quickly add psr4 autoloading entries to composer
  * [x] Document specific steps for modules
* Step 4 - Update codebase with references to newly namespaced classes
  * [x] Express the importance of keeping the .upgrade.yml file around.
  * [x]  Explain how to define ambiguous renaming
* Step 5 - Updating your codebase to use SilverStripe 4 API
  * [x] Document how to write your own warnings and replacements.
* Step 6 - Update your entry point
  * Not needed for module
* Step 7 - Update project structure
  * [x] Encourage people to switch to the `src` structure
* Step 8 - Switch to public web-root
  * Not needed for module
* Step 9 - Move away from hardcoded paths for referencing static assets
  * [x] Make clear this is mandatory for module and explain how.
* Step 10 - Update database class references
  * [x] Mention this is mandatory for module.
* Extra steps
  * [ ] ~Explain how to update unit test.~
  * [x] Keep updating your code afterwards.
  * [x] Write migration tasks

# Related PRs
* [x] https://github.com/silverstripe/silverstripe-framework/pull/8796
* [x] https://github.com/silverstripe/silverstripe-upgrader/pull/156

**Comment by sminnee** [comment]
Perhaps you could rename "all-in-one" to "upgrade-project" and call this "upgrade-module"

**Comment by chillu** [comment]
I think for now, just aim to make it clear in the upgrade instructions which steps module maintainers should keep or skip when going through an upgrade. Is that something you can roll into your current upgrading docs rewrite, or does it need a separate card?

Overall, I'd expect the average module maintainer to be a bit more hands-on with an upgrade compared to the average project dev.  My assumption is that `add-namespace` already works for modules, since they're just a folder?

**Comment by maxime-rainville** [comment]
I haven't tried it, but `add-namespace`, `upgrade` and `inspect` should all work just fine on packages. So the upgrader as-it-stands still provide plenty of value for package maintainer.

**Comment by chillu** [comment]
Related: https://github.com/silverstripe/silverstripe-upgrader/issues/134

@sunnysideup has written a whole tool on top of upgrader for this, maybe we can bring some of this into the main tool? https://github.com/sunnysideup/silverstripe-upgrade_to_silverstripe_4

We'll likely need a separate upgrading guide for modules (even if that means some copy-paste): https://docs.silverstripe.org/en/4/upgrading/

**Comment by maxime-rainville** [comment]
The more I look at the recompose command in the context of a module, the more I think it doesn't make sense to run when upgrading a module:
* The average module will have a lot less dependencies than the average project, making it a lot easier to update your dependencies by hand ;
* Modules should not reference recipes, they should reference specific pacakges ;
* recompose try to fix you to specific version of packages compatible with the recipe-core constraint you give it, module should be much more open ended in terms of their constraint ;
* as a module maintainer, you probably need to be much more aware of dependencies your module is using any way.

I could image writing a recompose command that wouldn't be completely useless in a module upgrade context, but that would involve scrapping/rewritting a big chunk of the existing command. Which would take more time than his reasonable for this job.

**Comment by maxime-rainville** [comment]
I got this thing almost done now. I fix a bunch of mistakes on how to reference static assets in the original upgrade guide.

I'm thinking it might be worthwhile adding a dedicated section in the project upgrade guide to include how to upgrade unit tests.

**Comment by maxime-rainville** [comment]
Blocked until @bergice comes back from his holiday.
